### PR TITLE
V6 support

### PR DESCRIPTION
**Pull request by rahulkp220**
Added Julia v6

### CODE REVIEW

**Comment by yuyichao** [comment]
Please update existing PR instead of opening new one everytime.

**Comment by rahulkp220** [comment]
I was actually using this on Julia 0.6 , before even I updated the build CI, therefore I thought to open up a PR.

**Comment by rahulkp220** [comment]
Hi, Any updates on whether this will be merged? Or I need to add if anything missing?

**Comment by omus** [comment]
Can be closed. Looks like this was encompassed by https://github.com/JuliaIO/LightXML.jl/pull/78

**Pull request closed without merging**
