### PR TITLE
Use BinaryProvider for binaries

### LINKED ISSUE #56: ubuntu 16.04 libxml2 troubles
Pkg.add("LightXML") need install libxml2 manualy via sudo apt-get install libxml2-dev 

see discusion https://groups.google.com/d/topic/julia-users/BH-xHZWqItY/discussion

### LINKED ISSUE #84: Could not load library "libxml2"
On Julia 0.6 LightXML.jl works fine, but  on Julia 0.7 I get an error `libxml2` could not be loaded:

```
(v0.7) pkg> add LightXML
  Updating registry at `~/.julia/registries/General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
 Resolving package versions...
  Updating `~/.julia/environments/v0.7/Project.toml`
  [9c8b4983] + LightXML v0.6.1
  Updating `~/.julia/environments/v0.7/Manifest.toml`
  [e1450e63] + BufferedStreams v0.4.1
  [0862f596] + HTTPClient v0.2.1
  [b27032c2] + LibCURL v0.2.2
  [522f3ed2] + LibExpat v0.4.2
  [2ec943e9] + Libz v0.2.4
  [9c8b4983] + LightXML v0.6.1
  [c17dfb99] + WinRPM v0.3.2

julia> using LightXML

julia> XMLDocument()
ERROR: error compiling Type: could not load library "libxml2"
libxml2.so: cannot open shared object file: No such file or directory
Stacktrace:
 [1] top-level scope at none:0
```

Version:

```
julia> versioninfo()
Julia Version 0.7.0-beta2.81
Commit fdad505 (2018-07-23 04:14 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E3-1230 v5 @ 3.40GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, skylake)
```

### PR DESCRIPTION
**Pull request by ararslan**
This uses the same builder as EzXML.

Fixes #56
Fixes #84

### CODE REVIEW

**Comment by tkelman** [comment]
Can you make this just the BinaryProvider change and hold off on using Appveyor.jl for a separate PR? It's doing some things it shouldn't be doing.

**Comment by ararslan** [comment]
Sure thing. I've changed the second commit to just add 0.7 lines to the Travis and AppVeyor configs.

**Comment by ararslan** [comment]
This fixes a couple of open issues, it passes all tests, and is blocking some time-sensitive work elsewhere, so I'm going to go ahead and merge.

**Comment by tkelman** [comment]
What does it fix exactly? And what other work depends on it? Please be more specific.

**Comment by tkelman** [comment]
Part of this is that the package depends on a feature which was deleted for no good reason and against objections upstream. That never got fixed where it should have been dealt with?

**Comment by ararslan** [comment]
> And what other work depends on it?

Internal AWS stuff.

> the package depends on a feature which was deleted for no good reason and against objections upstream

Which is that?

**Comment by ararslan** [comment]
> What does it fix exactly?

See linked issues

**Comment by tkelman** [comment]
soname handling in ccall / dlopen - that's the only reason this wouldn't work on 0.7 as-is, I believe

**Comment by ararslan** [comment]
Oh, _that_. 😆 Yeah. Luckily this also fixes the issue, since the `libxml2` constant defined by BinaryProvider points to the fully qualified and versioned library, so we don't need to rely on internal mapping.

Another 0.7 issue is that WinRPM doesn't work, and there's currently no way to specify platform-specific dependencies with Pkg3, so `Pkg.build("WinRPM")` runs and fails on every platform.

**Comment by tkelman** [comment]
> there's currently no way to specify platform-specific dependencies with Pkg3

Is https://github.com/JuliaLang/Pkg.jl/issues/165 realistically going to happen in some way? WinRPM shouldn't be that far from working on 0.7, at least on Windows.

**Comment by ararslan** [comment]
It's slated for inclusion in 0.7.0-rc1, so hopefully?

**Pull request merged**
